### ISSUE TITLE
Issueモデルにバリデーションを追加する 

### ISSUE THREAD

**Issue by ukitazume** [sitateru/kpt#1]
- [ ]  `title` を必須にする
- [ ] `status` のデフォルトをproblemにする
- [ ] それに付随して、コントローラーのvalidationエラー時のrspecを追加する

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 

>`status`のデフォルトをproblemにする

こちらですがDBデフォルトを使用しての実装でよろしかったでしょうか？

**Comment by ukitazume** [comment]
@orihakat05 OKです！

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
ご回答ありがとうございます、対応します。
