### ISSUE TITLE
Issueのソート機能

### ISSUE THREAD

**Issue by ukitazume** [sitateru/kpt#14]
Issueを更新日順に並び替えられるインターフェースをAPIに追加する

**Comment by tibaraki** [comment]
@ukitazume 
こちら#17のransack導入で機能的には包含されてしまうかと思いますが、個別にIssueとしている意図はありますでしょうか。

**Comment by ukitazume** [comment]
@tibaraki ransackにパスしちゃっているのいいと思いました！
