### ISSUE TITLE
Issueの内容を変更/削除するAPIを追加

### ISSUE THREAD

**Issue by ukitazume** [sitateru/kpt#2]
- [ ] 既存のイシューを更新するAPIを追加する
- [ ] 既存のイシューを削除するAPIを追加する
- [ ] issueモデルの削除は論理削除とする

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
>issueモデルの削除は論理削除とする

論理削除ですが追加のgemを利用しての対応でもよろしかったでしょうか？
良い場合は以下を使用しようかと考えております。
https://github.com/alfa-jpn/kakurenbo-puti

**Comment by ukitazume** [comment]
@orihakat05 gem使用してよいです。PRに、gemの選定理由を添えてください。

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
gem使用可と選定理由、承知しました、対応します。

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
issueのストロングパラメータについて１点相談させてください。
params.requireを使用して「issue」としてまとめたいのですがよろしいでしょうか？

```ruby
params.require(:issue).permit(:title, :body, :status)
```

**Comment by ukitazume** [comment]
@orihakat05 そうですね！該当コントローラーにて、private methodとして一つ用意してください。

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
ご回答ありがとうございます、対応いたします。

こちらのissueほとんど実装完了しておりますが今PRすると
「「Issueモデルにバリデーションを追加する」のissueを実装しました #6」とコンフリクト
しそうですので上記ご確認いただき、マージ完了後にPRいたします。

**Comment by ukitazume** [comment]
@orihakat05  WIPをつけて、PRしていただいても大丈夫ですよ！　おくれましたが、　#6 コメントしました。

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
ご回答ありがとうございます、タイトルのプレフィックスに`[WIP]`をつけてPRさせていただきます。
また #6 のレビューありがとうございます、確認します。

**Comment by ukitazume** [comment]
@orihakat05 遅くなりました。ありがとうございます！明日確認いたします。
