### ISSUE TITLE
coverallを追加し、テストカバレッジを表示する

### ISSUE THREAD

**Issue by ukitazume** [sitateru/kpt#3]
- [ ] simplecovをrspec に導入する
- [ ] coverallにこのリポジトリを追加し、バッチをREADMEに足す

**Comment by ukitazume** [comment]
depend #4

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
>simplecovをrspec に導入する

テスト実行時に生成される /coverage 配下はコミット対象外でよろしかったでしょうか？

**Comment by ukitazume** [comment]
@orihakat05  そうですね！　コミット対象外でお願いします〜！ 👍

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
承知しました、対象外とするようにします。
