### ISSUE TITLE
CIを実装する

### ISSUE THREAD

**Issue by ukitazume** [sitateru/kpt#4]
- [ ] CircleCI or Werckerにて、自動的にテストを走らせるようにする

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 

CircleCIでkptリポジトリが「Contact repo admin」となって選択できませんのでご確認いだけますでしょうか？

<img width="1353" alt="2017-10-14 11 20 47" src="https://user-images.githubusercontent.com/11383401/31571662-0dc57208-b0d2-11e7-8e6a-90bf3d4769a6.png">

**Comment by ukitazume** [comment]
@orihakat05 このリポジトリの

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 
設定ありがとうございます、確認できましたので対応いたします。
