### ISSUE TITLE
branchの作成について確認です

### ISSUE THREAD

**Issue by orihakat05** [sitateru/kpt#5]
@ukitazume @aki-tate 

branchですがissuesごとに作成してよろしいでしょうか？

**Comment by ukitazume** [comment]
@orihakat05 そうですね！なるべく細かくPull Requestを出していただいた方が、レビューしやすいです。二つ同時に解決した方がよい場合は一つでもいいです!

**Comment by orihakat05** [comment]
@ukitazume @aki-tate 

休日にご回答ありがとうございます、承知しました。
git、githubでの運用経験がないため、不適切な対応ありましたご指摘のほど、よろしくお願いいたします

**Comment by ukitazume** [comment]
@orihakat05 ふと、さっき休日の答えないと、作業時間とれない可能性ありそうだなと思って、確認しましたw　よろしくお願いします！

**Comment by orihakat05** [comment]
@ukitazume @aki-tate
ご配慮ありがとうございます、大変助かります。
大体自分の環境で試してできたのでなんとか行けそうです。色々勉強になります。
